package com.tallerzapata.backend.application.budget;

import com.tallerzapata.backend.api.budget.BudgetComparisonDtos.*;
import com.tallerzapata.backend.api.budget.CasePartResponse;
import com.tallerzapata.backend.application.common.*;
import com.tallerzapata.backend.application.security.CaseAccessControlService;
import com.tallerzapata.backend.infrastructure.persistence.budget.*;
import com.tallerzapata.backend.infrastructure.persistence.casefile.*;
import com.tallerzapata.backend.infrastructure.persistence.provider.*;
import com.tallerzapata.backend.infrastructure.security.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class BudgetComparisonService {
    private static final Set<String> ELIGIBLE_ACTIONS = Set.of("A_VERIFICAR", "REEMPLAZAR", "REEMPLAZAR_Y_CARGAR", "REEMPLAZAR_Y_PINTAR");
    private static final Set<String> BILLING_CODES = Set.of("A", "C", "SIN_FACTURA");
    private static final Set<String> PAYMENT_CODES = Set.of("CONTADO", "TARJETA_1_PAGO_SIN_INTERES", "TARJETA_CUOTAS_SIN_INTERES");
    private final BudgetComparisonSnapshotRepository snapshots; private final BudgetComparisonPieceRepository pieces; private final BudgetComparisonOfferRepository offers; private final BudgetComparisonProviderRepository providerColumns; private final BudgetComparisonPriceRepository prices; private final BudgetRepository budgets; private final BudgetItemRepository budgetItems; private final CasePartRepository caseParts; private final CaseRepository cases; private final ProviderRepository providers; private final CurrentUserService users; private final CaseAccessControlService access;
    public BudgetComparisonService(BudgetComparisonSnapshotRepository snapshots, BudgetComparisonPieceRepository pieces, BudgetComparisonOfferRepository offers, BudgetComparisonProviderRepository providerColumns, BudgetComparisonPriceRepository prices, BudgetRepository budgets, BudgetItemRepository budgetItems, CasePartRepository caseParts, CaseRepository cases, ProviderRepository providers, CurrentUserService users, CaseAccessControlService access) { this.snapshots=snapshots; this.pieces=pieces; this.offers=offers; this.providerColumns=providerColumns; this.prices=prices; this.budgets=budgets; this.budgetItems=budgetItems; this.caseParts=caseParts; this.cases=cases; this.providers=providers; this.users=users; this.access=access; }

    @Transactional public Snapshot createSnapshot(Long caseId, BudgetEntity budget, List<BudgetItemEntity> items, String key) {
        var previous=snapshots.findByCaseIdAndIdempotencyKey(caseId,key); if(previous.isPresent()) return snapshot(previous.get());
        BudgetComparisonSnapshotEntity snapshot=new BudgetComparisonSnapshotEntity(); snapshot.setCaseId(caseId); snapshot.setBudgetId(budget.getId()); snapshot.setGeneration(snapshots.findTopByCaseIdOrderByGenerationDesc(caseId).map(s->s.getGeneration()+1).orElse(1)); snapshot.setBudgetDate(budget.getBudgetDate()); snapshot.setBudgetVersion(budget.getCurrentVersion()); snapshot.setIdempotencyKey(key); snapshot.setMode("MATRIX"); snapshot=snapshots.save(snapshot);
        for(BudgetItemEntity item:items) if(Boolean.TRUE.equals(item.getActive())&&ELIGIBLE_ACTIONS.contains(item.getActionCode())) saveImportedPiece(snapshot.getId(), item);
        return snapshot(snapshot);
    }
    @Transactional(readOnly=true) public List<Snapshot> list(Long caseId) { require(caseId,"presupuesto.ver"); return snapshots.findByCaseIdOrderByGenerationDesc(caseId).stream().filter(s -> "MATRIX".equals(s.getMode())).map(this::snapshot).toList(); }
    @Transactional(readOnly=true) public Optional<Snapshot> findSnapshot(Long caseId, String key) { return snapshots.findByCaseIdAndIdempotencyKey(caseId, key).map(this::snapshot); }
    @Transactional(readOnly=true) public Detail detail(Long caseId,Long snapshotId) { require(caseId,"presupuesto.ver"); return detail(requireMatrixSnapshot(caseId,snapshotId)); }
    @Transactional(readOnly=true) public LegacyAudit legacyAudit(Long caseId, Long snapshotId) { require(caseId, "presupuesto.ver"); BudgetComparisonSnapshotEntity snapshot=requireSnapshot(caseId,snapshotId); if(!"LEGACY".equals(snapshot.getMode())) throw new ConflictException("El snapshot no es LEGACY"); List<BudgetComparisonPieceEntity> ps=pieces.findBySnapshotIdOrderByIdAsc(snapshotId); List<BudgetComparisonOfferEntity> os=ps.isEmpty()?List.of():offers.findByPieceIdInOrderByIdAsc(ps.stream().map(BudgetComparisonPieceEntity::getId).toList()); return new LegacyAudit(snapshot(snapshot), List.of(), os.stream().map(o -> new LegacyOffer(o.getId(),o.getProviderId(),o.getProviderSnapshot(),o.getAmount(),o.getBillingCode(),o.getPaymentMethodCode())).toList()); }
    @Transactional public CasePartResponse selectQuote(Long caseId, Long snapshotId, Long pieceId, Long columnId) { require(caseId,"presupuesto.crear"); BudgetComparisonSnapshotEntity snapshot=requireMatrixSnapshot(caseId,snapshotId); BudgetComparisonPieceEntity piece=requirePiece(snapshotId,pieceId); if(piece.getSourceBudgetItemId()==null) throw new ConflictException("La comparación no puede crear ni seleccionar un repuesto sin fuente canónica de presupuesto"); BudgetComparisonProviderEntity column=requireColumn(snapshotId,columnId); BudgetComparisonPriceEntity price=prices.findByPieceIdAndProviderColumnId(pieceId,columnId).orElseThrow(()->new ConflictException("Ingresá un precio antes de seleccionar la cotización")); CasePartEntity part=caseParts.findByCaseIdAndBudgetItemId(caseId,piece.getSourceBudgetItemId()).orElseThrow(()->new ConflictException("No existe el repuesto canónico para esta línea de presupuesto")); if(part.getSourceType()!=CasePartSourceType.BUDGET_ITEM||Boolean.TRUE.equals(part.getNonCanonical())) throw new ConflictException("La comparación sólo puede actualizar repuestos canónicos"); if(part.getProviderAssignmentOrigin()==ProviderAssignmentOrigin.MANUAL) throw new ConflictException("El proveedor del repuesto fue asignado manualmente y no puede ser reemplazado por la comparación"); part.setProviderId(column.getProviderId()); part.setFinalSupplier(column.getProviderSnapshot()); part.setFinalPrice(scale(price.getAmount())); part.setProviderAssignmentOrigin(ProviderAssignmentOrigin.BUDGET_ITEM); part=caseParts.save(part); return part(part); }
    @Transactional public Detail addProvider(Long caseId, Long snapshotId, ProviderRequest request) { AuthenticatedUser user=require(caseId,"presupuesto.crear"); access.requirePermission(user,"proveedor.ver"); BudgetComparisonSnapshotEntity snapshot=requireMatrixSnapshot(caseId,snapshotId); if(providerColumns.existsBySnapshotIdAndProviderId(snapshotId,request.providerId())) throw new ConflictException("El proveedor ya existe en esta comparación"); ProviderEntity provider=providers.findById(request.providerId()).orElseThrow(()->new ResourceNotFoundException("No existe el proveedor "+request.providerId())); if(!Boolean.TRUE.equals(provider.getActive())) throw new ConflictException("El proveedor está inactivo"); BudgetComparisonProviderEntity column=new BudgetComparisonProviderEntity(); column.setSnapshotId(snapshotId); column.setProviderId(provider.getId()); column.setProviderSnapshot(provider.getName()); column.setBillingCode(validateBilling(request.billingCode())); column.setPaymentMethodCode(validatePayment(request.paymentMethodCode())); providerColumns.save(column); return detail(snapshot); }
    @Transactional public Detail updateTerms(Long caseId, Long snapshotId, Long columnId, TermsRequest request) { require(caseId,"presupuesto.crear"); BudgetComparisonSnapshotEntity snapshot=requireMatrixSnapshot(caseId,snapshotId); BudgetComparisonProviderEntity column=requireColumn(snapshotId,columnId); column.setBillingCode(validateBilling(request.billingCode())); column.setPaymentMethodCode(validatePayment(request.paymentMethodCode())); return detail(snapshot); }
    @Transactional public void deleteProvider(Long caseId, Long snapshotId, Long columnId) { require(caseId,"presupuesto.crear"); requireMatrixSnapshot(caseId,snapshotId); providerColumns.delete(requireColumn(snapshotId,columnId)); }
    @Transactional public Detail upsertPrice(Long caseId, Long snapshotId, Long pieceId, Long columnId, PriceRequest request) { require(caseId,"presupuesto.crear"); BudgetComparisonSnapshotEntity snapshot=requireMatrixSnapshot(caseId,snapshotId); BudgetComparisonPieceEntity piece=requirePiece(snapshotId,pieceId); requireColumn(snapshotId,columnId); BudgetComparisonPriceEntity price=prices.findByPieceIdAndProviderColumnId(piece.getId(),columnId).orElseGet(BudgetComparisonPriceEntity::new); price.setPieceId(piece.getId()); price.setProviderColumnId(columnId); price.setAmount(scale(request.amount())); prices.save(price); return detail(snapshot); }
    @Transactional public void clearPrice(Long caseId, Long snapshotId, Long pieceId, Long columnId) { require(caseId,"presupuesto.crear"); requireMatrixSnapshot(caseId,snapshotId); requirePiece(snapshotId,pieceId); requireColumn(snapshotId,columnId); prices.findByPieceIdAndProviderColumnId(pieceId,columnId).ifPresent(prices::delete); }
    private Detail detail(BudgetComparisonSnapshotEntity snapshot) { List<BudgetComparisonPieceEntity> ps=pieces.findBySnapshotIdOrderByIdAsc(snapshot.getId()); List<BudgetComparisonProviderEntity> columns=providerColumns.findBySnapshotIdOrderByIdAsc(snapshot.getId()); Map<Long,List<BudgetComparisonPriceEntity>> byPiece=ps.isEmpty()?Map.of():prices.findByPieceIdInOrderByIdAsc(ps.stream().map(BudgetComparisonPieceEntity::getId).toList()).stream().collect(Collectors.groupingBy(BudgetComparisonPriceEntity::getPieceId)); BigDecimal subtotal=BigDecimal.ZERO; List<Piece> result=new ArrayList<>(); for(BudgetComparisonPieceEntity piece:ps) { List<BudgetComparisonPriceEntity> row=byPiece.getOrDefault(piece.getId(),List.of()); BigDecimal minimum=row.stream().map(BudgetComparisonPriceEntity::getAmount).min(Comparator.naturalOrder()).orElse(null); if(minimum!=null) subtotal=subtotal.add(minimum); result.add(new Piece(piece.getId(),piece.getDescription(),piece.getActionCode(),piece.getSourcePartValue(),piece.getOrigin(),row.stream().map(price -> new Cell(price.getProviderColumnId(),price.getAmount(),price.getAmount().compareTo(minimum)==0)).toList())); } return new Detail(snapshot(snapshot),columns.stream().map(c -> new ProviderColumn(c.getId(),c.getProviderId(),c.getProviderSnapshot(),c.getBillingCode(),c.getPaymentMethodCode(),prices.countByProviderColumnId(c.getId()))).toList(),result,scale(subtotal)); }
    private void saveImportedPiece(Long snapshotId, BudgetItemEntity item) { BudgetComparisonPieceEntity piece=new BudgetComparisonPieceEntity(); piece.setSnapshotId(snapshotId); piece.setSourceBudgetItemId(item.getId()); piece.setDescription(item.getAffectedPiece()); piece.setActionCode(item.getActionCode()); piece.setSourcePartValue(scale(item.getPartValue())); piece.setOrigin("IMPORTADA"); pieces.save(piece); }
    private Snapshot snapshot(BudgetComparisonSnapshotEntity s) { return new Snapshot(s.getId(),s.getGeneration(),s.getBudgetDate(),s.getBudgetVersion(),s.getMode(),pieces.findBySnapshotIdOrderByIdAsc(s.getId()).size()); }
    private AuthenticatedUser require(Long caseId,String permission) { AuthenticatedUser user=users.requireCurrentUser(); CaseEntity c=cases.findById(caseId).orElseThrow(()->new ResourceNotFoundException("No existe el caso "+caseId)); access.requireCaseAccess(user,c,permission); return user; }
    private BudgetComparisonSnapshotEntity requireSnapshot(Long caseId,Long id) { return snapshots.findByIdAndCaseId(id,caseId).orElseThrow(()->new ResourceNotFoundException("No existe el snapshot de comparación "+id)); }
    private BudgetComparisonSnapshotEntity requireMatrixSnapshot(Long caseId, Long id) { BudgetComparisonSnapshotEntity snapshot=requireSnapshot(caseId,id); if(!"MATRIX".equals(snapshot.getMode())) throw new ConflictException("El snapshot LEGACY sólo está disponible para auditoría"); return snapshot; }
    private BudgetComparisonPieceEntity requirePiece(Long snapshotId,Long id) { return pieces.findByIdAndSnapshotId(id,snapshotId).orElseThrow(()->new ResourceNotFoundException("No existe la pieza de comparación "+id)); }
    private BudgetComparisonProviderEntity requireColumn(Long snapshotId, Long id) { return providerColumns.findByIdAndSnapshotId(id,snapshotId).orElseThrow(()->new ResourceNotFoundException("No existe el proveedor de comparación "+id)); }
    private String validateBilling(String value) { String code=normalize(value); if(!BILLING_CODES.contains(code)) throw new ConflictException("billingCode no permitido: "+value); return code; }
    private String validatePayment(String value) { String code=normalize(value); if(!PAYMENT_CODES.contains(code)) throw new ConflictException("paymentMethodCode no permitido: "+value); return code; }
    private String normalize(String value) { return value==null?null:value.trim().toUpperCase(); } private BigDecimal scale(BigDecimal value) { return value.setScale(2,RoundingMode.HALF_UP); }
    private CasePartResponse part(CasePartEntity e) { return new CasePartResponse(e.getId(),e.getCaseId(),e.getBudgetItemId(),e.getDescription(),e.getPartCode(),e.getFinalSupplier(),e.getAuthorizedCode(),e.getStatusCode(),e.getPurchasedByCode(),e.getPaymentStatusCode(),e.getBudgetedPrice(),e.getFinalPrice(),e.getReceivedDate(),e.getUsed(),e.getReturned(),e.getProviderId(),e.getSourceType()==null?null:e.getSourceType().name(),e.getAccessoryWorkId(),e.getAccessory(),e.getNonCanonical(), List.of()); }
}
