CREATE TABLE documento_cargas (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    caso_id BIGINT UNSIGNED NULL,
    categoria_id BIGINT UNSIGNED NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    tamano_bytes BIGINT UNSIGNED NOT NULL,
    checksum_sha256 CHAR(64) NOT NULL,
    cantidad_chunks INT NOT NULL,
    siguiente_chunk INT NOT NULL DEFAULT 0,
    bytes_recibidos BIGINT UNSIGNED NOT NULL DEFAULT 0,
    subido_por BIGINT UNSIGNED NOT NULL,
    origen_codigo VARCHAR(50) NOT NULL,
    observaciones TEXT NULL,
    fecha_documento DATE NULL,
    estado VARCHAR(20) NOT NULL,
    documento_id BIGINT UNSIGNED NULL,
    expira_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_documento_cargas_public_id (public_id),
    KEY idx_documento_cargas_expira_at (estado, expira_at),
    CONSTRAINT fk_documento_cargas_caso FOREIGN KEY (caso_id) REFERENCES casos (id) ON DELETE CASCADE,
    CONSTRAINT fk_documento_cargas_categoria FOREIGN KEY (categoria_id) REFERENCES categorias_documentales (id),
    CONSTRAINT fk_documento_cargas_subido_por FOREIGN KEY (subido_por) REFERENCES usuarios (id),
    CONSTRAINT fk_documento_cargas_documento FOREIGN KEY (documento_id) REFERENCES documentos (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
