package com.tallerzapata.backend.application.casefile.cleasstate;
import com.tallerzapata.backend.application.common.ConflictException;
import com.tallerzapata.backend.infrastructure.persistence.casefile.*;
import com.tallerzapata.backend.infrastructure.persistence.cleasstate.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.Optional;
@Service
public class CleasEffectiveStateRecalculator {
 private final CaseRepository cases; private final CaseTypeRepository types; private final CleasEffectiveStateRepository states; private final CleasEffectiveStateHistoryRepository history; private final CleasStateFactsRepository facts; private final CleasEffectiveStateFactsLoader loader; private final CleasEffectiveStatePolicy policy=new CleasEffectiveStatePolicy();
 public CleasEffectiveStateRecalculator(CaseRepository cases,CaseTypeRepository types,CleasEffectiveStateRepository states,CleasEffectiveStateHistoryRepository history,CleasStateFactsRepository facts,CleasEffectiveStateFactsLoader loader){this.cases=cases;this.types=types;this.states=states;this.history=history;this.facts=facts;this.loader=loader;}
  @Transactional public void recalculate(Long caseId){CaseEntity c=cases.findByIdForUpdate(caseId).orElseThrow();if(!isCleas(c))return;Optional<CleasEffectiveStateEntity> found=states.findByCaseIdForUpdate(caseId);CleasEffectiveStateEntity state=found.orElseGet(()->newState(caseId));CleasEffectiveStatePolicy.CleasEffectiveState next=policy.evaluate(loader.load(c));if(next.procedureCode().equals(state.getProcedureCode())&&next.repairCode().equals(state.getRepairCode()))return;String priorProcedure=state.getProcedureCode(),priorRepair=state.getRepairCode();state.setProcedureCode(next.procedureCode());state.setRepairCode(next.repairCode());state.setRecalculatedAt(LocalDateTime.now());states.save(state);audit(caseId,priorProcedure,priorRepair,next,"RECALCULATION",null,null);}
  @Transactional public void override(Long caseId,String domain,String stateCode,Long actor,String reason){requireReason(reason,actor);CaseEntity c=cases.findByIdForUpdate(caseId).orElseThrow();if(!isCleas(c))return;CleasEffectiveStateEntity state=states.findByCaseIdForUpdate(caseId).orElseGet(()->newState(caseId));String priorProcedure=state.getProcedureCode(),priorRepair=state.getRepairCode();String priorOverride="tramite".equals(domain)?state.getProcedureTerminalOverrideCode():state.getRepairTerminalOverrideCode();if("tramite".equals(domain))state.setProcedureTerminalOverrideCode(stateCode);else state.setRepairTerminalOverrideCode(stateCode);CleasEffectiveStatePolicy.CleasEffectiveState next=policy.evaluate(loader.load(c));state.setProcedureCode(next.procedureCode());state.setRepairCode(next.repairCode());state.setRecalculatedAt(LocalDateTime.now());states.save(state);auditOverride(caseId,priorProcedure,priorRepair,next,stateCode==null?"OVERRIDE_REVERT":"OVERRIDE",actor,reason,"tramite".equals(domain)?"TRAMITE":"REPARACION",priorOverride,stateCode);}
 @Transactional public void recordAgreement(Long caseId,LocalDate date){if(!isCleas(caseId))return;CleasStateFactsEntity f=facts.findById(caseId).orElseGet(()->newFacts(caseId));f.setAgreementDate(date);facts.save(f);recalculate(caseId);}
 @Transactional public void markNoRepair(Long caseId,String reason,Long actor){requireReason(reason,actor);requireCleas(caseId);CleasStateFactsEntity f=facts.findById(caseId).orElseGet(()->newFacts(caseId));if(Boolean.TRUE.equals(f.getNoRepairActive()))return;f.setNoRepairActive(true);f.setNoRepairReason(reason.trim());f.setNoRepairAt(LocalDateTime.now());f.setNoRepairActorUserId(actor);facts.save(f);recalculate(caseId);auditAction(caseId,"NO_REPAIR",actor,reason);}
 @Transactional public void revertNoRepair(Long caseId,String reason,Long actor){requireReason(reason,actor);requireCleas(caseId);CleasStateFactsEntity f=facts.findById(caseId).orElseThrow(()->new ConflictException("El caso no tiene una accion no debe repararse"));if(!Boolean.TRUE.equals(f.getNoRepairActive()))return;f.setNoRepairActive(false);f.setNoRepairRevertedAt(LocalDateTime.now());f.setNoRepairRevertedActorUserId(actor);f.setNoRepairRevertedReason(reason.trim());facts.save(f);recalculate(caseId);auditAction(caseId,"NO_REPAIR_REVERT",actor,reason);}
 @Transactional public void markUrgentRepaired(Long caseId,String reason,Long actor){requireReason(reason,actor);requireCleas(caseId);CaseEntity c=cases.findByIdForUpdate(caseId).orElseThrow();if(loader.load(c).presentedAt()!=null)throw new ConflictException("La reparacion urgente solo puede registrarse antes de la presentacion");CleasStateFactsEntity f=facts.findById(caseId).orElseGet(()->newFacts(caseId));if(Boolean.TRUE.equals(f.getUrgentRepairActive()))return;f.setUrgentRepairActive(true);f.setUrgentRepairReason(reason.trim());f.setUrgentRepairAt(LocalDateTime.now());f.setUrgentRepairActorUserId(actor);facts.save(f);c.setPriorityCode("URGENTE");cases.save(c);recalculate(caseId);auditAction(caseId,"URGENT_REPAIR",actor,reason);}
  private void auditAction(Long id,String cause,Long actor,String reason){CleasEffectiveStatePolicy.CleasEffectiveState current=policy.evaluate(loader.load(cases.findByIdForUpdate(id).orElseThrow()));audit(id,null,null,current,cause,actor,reason);} private void audit(Long id,String pp,String pr,CleasEffectiveStatePolicy.CleasEffectiveState next,String cause,Long actor,String reason){auditOverride(id,pp,pr,next,cause,actor,reason,null,null,null);} private void auditOverride(Long id,String pp,String pr,CleasEffectiveStatePolicy.CleasEffectiveState next,String cause,Long actor,String reason,String dimension,String priorOverride,String newOverride){CleasEffectiveStateHistoryEntity h=new CleasEffectiveStateHistoryEntity();h.setCaseId(id);h.setPriorProcedureCode(pp);h.setPriorRepairCode(pr);h.setNewProcedureCode(next.procedureCode());h.setNewRepairCode(next.repairCode());h.setCause(cause);h.setActorUserId(actor);h.setReason(reason);h.setOverrideDimension(dimension);h.setOverridePriorCode(priorOverride);h.setOverrideNewCode(newOverride);h.setCreatedAt(LocalDateTime.now());history.save(h);} private CleasEffectiveStateEntity newState(Long id){CleasEffectiveStateEntity state=new CleasEffectiveStateEntity();state.setCaseId(id);return state;} private CleasStateFactsEntity newFacts(Long id){CleasStateFactsEntity f=new CleasStateFactsEntity();f.setCaseId(id);f.setNoRepairActive(false);f.setUrgentRepairActive(false);return f;} private boolean isCleas(Long id){return cases.findByIdForUpdate(id).map(this::isCleas).orElse(false);} private boolean isCleas(CaseEntity c){return types.findById(c.getCaseTypeId()).map(t->"CLEAS".equalsIgnoreCase(t.getCode())).orElse(false);} private void requireCleas(Long id){if(!isCleas(id))throw new ConflictException("La accion solo aplica a casos CLEAS");} private void requireReason(String r,Long a){if(a==null||r==null||r.isBlank())throw new ConflictException("Motivo y actor son obligatorios");}
}
