package com.tallerzapata.backend.application.casefile.cleasstate;
import com.tallerzapata.backend.application.cleas.CleasSettlementPolicy;
import com.tallerzapata.backend.infrastructure.persistence.budget.CasePartRepository;
import com.tallerzapata.backend.infrastructure.persistence.casefile.CaseEntity;
import com.tallerzapata.backend.infrastructure.persistence.cleasstate.CleasStateFactsRepository;
import com.tallerzapata.backend.infrastructure.persistence.finance.FinancialMovementEntity;
import com.tallerzapata.backend.infrastructure.persistence.finance.FinancialMovementRepository;
 import com.tallerzapata.backend.infrastructure.persistence.insurance.*;
import com.tallerzapata.backend.infrastructure.persistence.operation.*;
import com.tallerzapata.backend.infrastructure.persistence.workflow.WorkflowStateRepository;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Component;
import java.math.BigDecimal;
import java.util.*;
@Component
public class CleasEffectiveStateFactsLoader {
  private final CleasStateFactsRepository facts; private final InsuranceProcessingRepository processing; private final CaseCleasRepository cleas; private final CaseInsuranceRepository caseInsurance; private final CleasSettlementPolicy settlement; private final WorkflowStateRepository workflow; private final CasePartRepository parts; private final RepairAppointmentRepository appointments; private final VehicleOutcomeRepository outcomes; private final FinancialMovementRepository movements;
  public CleasEffectiveStateFactsLoader(CleasStateFactsRepository facts, InsuranceProcessingRepository processing, CaseCleasRepository cleas, CaseInsuranceRepository caseInsurance, CleasSettlementPolicy settlement, WorkflowStateRepository workflow, CasePartRepository parts, RepairAppointmentRepository appointments, VehicleOutcomeRepository outcomes, FinancialMovementRepository movements) {this.facts=facts;this.processing=processing;this.cleas=cleas;this.caseInsurance=caseInsurance;this.settlement=settlement;this.workflow=workflow;this.parts=parts;this.appointments=appointments;this.outcomes=outcomes;this.movements=movements;}
 public CleasEffectiveStateFacts load(CaseEntity entity) {
  Long id=entity.getId(); var stateFacts=facts.findById(id).orElse(null); var definition=cleas.findByCaseId(id).orElse(null); var insurance=processing.findByCaseId(id).orElse(null); var agreement=stateFacts==null?null:stateFacts.getAgreementDate(); var amount=insurance==null?BigDecimal.ZERO:money(insurance.getAgreedAmount()); var distribution=settlementEligible(definition)?settlement.settle(definition, amount):null; List<FinancialMovementEntity> all=movements.findByCaseId(id, Sort.unsorted()); List<RepairAppointmentEntity> allAppointments=appointments.findByCaseId(id, Sort.unsorted()); var outcome=outcomes.findByCaseId(id, Sort.unsorted()).stream().max(Comparator.comparing(VehicleOutcomeEntity::getOutcomeAt).thenComparing(VehicleOutcomeEntity::getId)).orElse(null);
    Long insurerId=caseInsurance.findByCaseId(id).map(CaseInsuranceEntity::getInsuranceCompanyId).orElse(null); BigDecimal companyPaid=sumCompany(all, insurerId); BigDecimal customerPaid=sum(all, "CLIENTE", "FRANQUICIA");
  return new CleasEffectiveStateFacts(insurance==null?null:insurance.getPresentedAt(), documentationComplete(entity), accepted(insurance==null?null:insurance.getQuotationStatusCode()), agreement, definition==null?null:definition.getScopeCode(), definition==null?null:definition.getOpinionCode(), entity.getClosedAt()!=null && "DANIO_TOTAL".equals(code(definition==null?null:definition.getScopeCode())) && "EN_CONTRA".equals(code(definition==null?null:definition.getOpinionCode())), distribution==null?BigDecimal.ZERO:distribution.amountToBillCompany(), companyPaid, distribution==null?BigDecimal.ZERO:distribution.customerChargeAmount(), customerPaid, distribution==null?BigDecimal.ZERO:distribution.companyRequiredAmount(), definition==null?null:definition.getCompanyFranchisePaymentStatusCode(), stateFacts!=null&&Boolean.TRUE.equals(stateFacts.getNoRepairActive()), stateFacts!=null&&Boolean.TRUE.equals(stateFacts.getUrgentRepairActive()), outcome==null?null:new CleasEffectiveStateFacts.OutcomeFact(repaired(outcome), Boolean.TRUE.equals(outcome.getShouldReenter()), satisfied(outcome, allAppointments)), allAppointments.stream().anyMatch(this::normalAppointment), parts.findByCaseIdOrderByIdAsc(id).stream().map(p->new CleasEffectiveStateFacts.PartFact(p.getAuthorizedCode(),p.getStatusCode())).toList());
 }
  private boolean settlementEligible(CaseCleasEntity definition){if(definition==null)return false;String scope=code(definition.getScopeCode()), opinion=code(definition.getOpinionCode());return "A_FAVOR".equals(opinion)||("FRANQUICIA".equals(scope)&&"EN_CONTRA".equals(opinion));}
   private BigDecimal sumCompany(List<FinancialMovementEntity> values,Long insurerId){if(insurerId==null)return BigDecimal.ZERO;return values.stream().filter(v->"ASEGURADORA".equals(code(v.getFlowOriginCode()))&&"COMPANIA".equals(code(v.getCancellationTypeCode()))&&insurerId.equals(v.getCounterpartyCompanyId())).map(this::signed).reduce(BigDecimal.ZERO,BigDecimal::add);} private BigDecimal sum(List<FinancialMovementEntity> values,String origin,String cancellation){return values.stream().filter(v->origin.equals(code(v.getFlowOriginCode()))&&cancellation.equals(code(v.getCancellationTypeCode()))).map(this::signed).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private BigDecimal signed(FinancialMovementEntity v){BigDecimal amount=money(v.getNetAmount()); return "INGRESO".equals(code(v.getMovementTypeCode()))||("AJUSTE".equals(code(v.getMovementTypeCode()))&&amount.signum()>=0)?amount:amount.negate();}
  private boolean documentationComplete(CaseEntity e){return e.getCurrentDocumentationStateId()!=null&&workflow.findById(e.getCurrentDocumentationStateId()).map(s->"DOCUMENTACION".equals(code(s.getDomain()))&&"COMPLETA".equals(code(s.getCode()))).orElse(false);} private boolean accepted(String v){return "ACEPTADA".equals(code(v))||"ACORDADA".equals(code(v));} private boolean repaired(VehicleOutcomeEntity v){return Boolean.TRUE.equals(v.getDefinitive())&&!Boolean.TRUE.equals(v.getShouldReenter());} private boolean satisfied(VehicleOutcomeEntity o,List<RepairAppointmentEntity> a){return o.getReentryAppointmentId()!=null&&a.stream().anyMatch(x->o.getReentryAppointmentId().equals(x.getId())&&current(x));} private boolean normalAppointment(RepairAppointmentEntity a){return !Boolean.TRUE.equals(a.getReentry())&&current(a);} private boolean current(RepairAppointmentEntity a){return "PENDIENTE".equals(code(a.getStatusCode()))||"REPROGRAMADO".equals(code(a.getStatusCode()));} private String code(String v){return v==null?"":v.trim().toUpperCase();} private BigDecimal money(BigDecimal v){return v==null?BigDecimal.ZERO:v;}
}
