import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const api={list:vi.fn(),detail:vi.fn(),select:vi.fn(),provider:vi.fn(),terms:vi.fn(),price:vi.fn(),clear:vi.fn(),remove:vi.fn(),download:vi.fn()};
vi.mock('@/modules/cases/api/budget-comparison-api',()=>({listBudgetComparisons:(...a)=>api.list(...a),getBudgetComparison:(...a)=>api.detail(...a),addComparisonProvider:(...a)=>api.provider(...a),updateComparisonTerms:(...a)=>api.terms(...a),saveComparisonPrice:(...a)=>api.price(...a),clearComparisonPrice:(...a)=>api.clear(...a),selectComparisonQuote:(...a)=>api.select(...a),deleteComparisonProvider:(...a)=>api.remove(...a),downloadBudgetComparisonPdf:(...a)=>api.download(...a)}));
vi.mock('@/modules/cases/api/providers-api',()=>({searchProviders:vi.fn()})); vi.mock('sonner',()=>({toast:{error:vi.fn()}}));
const matrix={snapshot:{id:7,mode:'MATRIX'},providers:[{id:4,providerId:12,name:'Norte',billingCode:'A',paymentMethodCode:'CONTADO',priceCount:1},{id:5,providerId:13,name:'Sur',billingCode:'C',paymentMethodCode:'TARJETA_CUOTAS_SIN_INTERES',priceCount:1}],pieces:[{id:9,description:'Óptica',actionCode:'REEMPLAZAR',origin:'IMPORTADA',cells:[{providerColumnId:4,amount:100,minimum:true},{providerColumnId:5,amount:100,minimum:true}]}],bestPriceSubtotal:100};
const renderPanel=(props={})=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><BudgetComparisonPanel caseId="42" canViewProviders {...props}/></QueryClientProvider>);
const {BudgetComparisonPanel}=await import('./budget-comparison-panel');
 describe('BudgetComparisonPanel matrix',()=>{beforeEach(()=>{vi.clearAllMocks();api.list.mockResolvedValue([{id:1,generation:9,mode:'LEGACY'},{id:7,generation:2,budgetDate:'2026-08-23',mode:'MATRIX'}]);api.detail.mockResolvedValue(matrix);api.select.mockResolvedValue({});api.provider.mockResolvedValue(matrix);api.terms.mockResolvedValue(matrix);api.price.mockResolvedValue(matrix);api.clear.mockResolvedValue();api.remove.mockResolvedValue();api.download.mockResolvedValue(new Blob(['pdf']));URL.createObjectURL=vi.fn(()=> 'blob:comparison');URL.revokeObjectURL=vi.fn();});
 it('orders headers, pieces, payment terms, and subtotal in the desktop matrix',async()=>{renderPanel();await screen.findAllByText('Óptica');const table=screen.getByRole('table');const text=table.textContent;expect(text.indexOf('REPUESTO')).toBeLessThan(text.indexOf('PROVEEDOR 1'));expect(text.indexOf('PROVEEDOR 1')).toBeLessThan(text.indexOf('Óptica'));expect(text.indexOf('Óptica')).toBeLessThan(text.indexOf('Facturación'));expect(text.indexOf('Facturación')).toBeLessThan(text.indexOf('Medio de Pago'));expect(text.indexOf('Medio de Pago')).toBeLessThan(text.indexOf('Subtotal mejor precio:'));expect(screen.getByRole('columnheader',{name:/proveedor 1.*norte/i})).toBeInTheDocument();expect(screen.getByLabelText('Facturación de Norte')).toBeInTheDocument();expect(screen.getByLabelText('Medio de pago de Sur')).toBeInTheDocument();expect(screen.queryByRole('option',{name:/generación 9/i})).not.toBeInTheDocument();expect(screen.getAllByText('Mejor precio')).toHaveLength(4);expect(screen.getByRole('rowheader',{name:'Subtotal mejor precio:'})).toBeInTheDocument();expect(table).toHaveTextContent('$ 100,00');});
 it('clears a price through the editor and confirms destructive provider deletion',async()=>{const user=userEvent.setup();renderPanel();await screen.findAllByText('Óptica');await user.click(screen.getAllByRole('button',{name:/mejor precio/i})[0]);await user.clear(screen.getByLabelText('Importe ARS'));await user.click(screen.getByRole('button',{name:'Guardar'}));await waitFor(()=>expect(api.clear).toHaveBeenCalledWith('42',7,9,4));await user.click(screen.getByRole('button',{name:'Quitar Norte'}));expect(screen.getByRole('dialog')).toHaveTextContent('1 precios');await user.click(screen.getByRole('button',{name:'Quitar proveedor'}));await waitFor(()=>expect(api.remove).toHaveBeenCalledWith('42',7,4));});
 it('edits terms, restores focus after Escape, and labels the global-provider dialog',async()=>{const user=userEvent.setup();renderPanel();await screen.findAllByText('Óptica');await user.selectOptions(screen.getByLabelText('Facturación de Norte'),'C');await user.click(screen.getAllByRole('button',{name:'Guardar términos'})[0]);await waitFor(()=>expect(api.terms).toHaveBeenCalledWith('42',7,4,{billingCode:'C',paymentMethodCode:'CONTADO'}));const priceButton=screen.getAllByRole('button',{name:/mejor precio/i})[0];await user.click(priceButton);expect(screen.getByLabelText('Importe ARS')).toHaveFocus();await user.keyboard('{Escape}');expect(priceButton).toHaveFocus();await user.click(screen.getAllByRole('button',{name:'Agregar proveedor'})[0]);expect(screen.getByRole('textbox',{name:'Proveedor global'})).toHaveFocus();fireEvent.change(screen.getByRole('textbox',{name:'Proveedor global'}),{target:{value:'Central'}});expect(screen.getAllByRole('button',{name:'Agregar proveedor'})[1]).toBeDisabled();});
  it('keeps desktop and mobile matrix representations available and downloads the comparison PDF',async()=>{const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});const user=userEvent.setup();renderPanel();await screen.findAllByText('Óptica');expect(screen.getByRole('table')).toBeInTheDocument();expect(screen.getAllByRole('article')).toHaveLength(1);await user.click(screen.getByRole('button',{name:/descargar pdf/i}));await waitFor(()=>expect(api.download).toHaveBeenCalledWith('42',7));expect(URL.createObjectURL).toHaveBeenCalled();expect(click).toHaveBeenCalled();click.mockRestore();});
  it('loads EXTRA snapshots with the context query and selects a desktop quote',async()=>{api.list.mockResolvedValue([{id:7,generation:2,budgetDate:'2026-08-23',mode:'MATRIX',context:'EXTRA'}]);const user=userEvent.setup();renderPanel({context:'EXTRA'});await screen.findAllByText('Óptica');expect(api.list).toHaveBeenCalledWith('42','EXTRA');await user.click(screen.getAllByRole('button',{name:/aplicar cotización: óptica - norte/i})[0]);await waitFor(()=>expect(api.select).toHaveBeenCalledWith('42',7,9,4));});
});
