import { useState as useReactState } from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ExtraBudgetEditorPanel } from './extra-budget-editor-panel';
import { ExtraBudgetPaymentsPanel } from './extra-budget-payments-panel';

let response;
const activation = vi.fn(); const saveDraft = vi.fn(); const confirm = vi.fn(); const getExtraBudget = vi.fn(); const invalidateQueries = vi.fn().mockResolvedValue(undefined); const setQueryData = vi.fn((_, data) => { response = data; });
vi.mock('@tanstack/react-query', () => ({
  useQuery: (options) => options.enabled === false ? { data: undefined, isLoading: false } : { data: options.queryKey?.[1] === 'catalogs' ? { actionCodes: [{ code: 'REPARAR', name: 'Reparar' }, { code: 'REEMPLAZAR', name: 'Reemplazar' }], damageLevelCodes: [{ code: 'LEVE', name: 'Leve' }] } : response, isLoading: false },
  useMutation: ({ mutationFn, onSuccess, onError, onSettled }) => { const [isPending] = useReactState(false); return { isPending, mutate: async (value) => { try { await onSuccess?.(await mutationFn(value)); } catch (error) { await onError?.(error, value); } finally { await onSettled?.(); } } }; },
  useQueryClient: () => ({ invalidateQueries, setQueryData }),
}));
vi.mock('@/modules/cases/api/extra-budget-api', () => ({
  extraBudgetQueryKey: (caseId) => ['cases', String(caseId), 'extra-budget'], getExtraBudget: (...args) => getExtraBudget(...args), setExtraBudgetActivation: (...args) => activation(...args), saveExtraBudgetDraft: (...args) => saveDraft(...args), presentExtraBudget: vi.fn(), confirmExtraBudget: (...args) => confirm(...args), downloadExtraBudgetPdf: vi.fn(),
}));
vi.mock('@/modules/cases/api/budget-catalogs-api', () => ({ getBudgetCatalogs: vi.fn() }));
vi.mock('@/modules/cases/components/budget-comparison-panel', () => ({ BudgetComparisonPanel: ({ context }) => <div data-testid="common-comparison">Matriz común {context}</div> }));
vi.mock('sonner', () => ({ toast: { success: vi.fn(), error: vi.fn() } }));

const draft = (overrides = {}) => ({ versionLock: 9, currentVersion: 1, currentStatus: 'BORRADOR', customerConfirmation: 'PENDIENTE', activation: { active: true, requiresDeactivationConfirmation: true }, paidAmount: 0, balance: 0, versions: [{ id: 1, number: 1, status: 'BORRADOR', generalLaborAmount: 0, generalLaborVatApplies: false, notes: '', partsTotal: 0, laborWithoutVat: 0, laborVat: 0, total: 0, items: [{ itemId: 1, visualOrder: 1, affectedPiece: 'Puerta', actionCode: 'REPARAR', damageLevelCode: 'LEVE', partsAmount: 0, active: true }] }], ...overrides });

describe('presupuesto extra V78', () => {
  beforeEach(() => { vi.clearAllMocks(); response = draft(); activation.mockResolvedValue(response); getExtraBudget.mockResolvedValue(response); saveDraft.mockResolvedValue(response); confirm.mockResolvedValue(response); });
  it.each(['PARTICULAR'])('remains absent for %s and does not affect the main budget', (caseTypeCode) => { render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode={caseTypeCode} />); expect(screen.queryByText('Presupuesto de trabajos extras')).toBeNull(); });
  it.each(['TODO_RIESGO', 'GRANIZO', 'CLEAS'])('shows only for %s', (caseTypeCode) => { render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode={caseTypeCode} />); expect(screen.getByRole('heading', { name: 'Presupuesto de trabajos extras' })).toBeInTheDocument(); });
  it('saves one complete row without task, provider, comparison, confirmation, labor, or IVA requirements', async () => { render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); expect(screen.queryByLabelText('Aplicar IVA')).toBeNull(); expect(screen.getByText('IVA').parentElement).toHaveTextContent('0'); fireEvent.click(screen.getByRole('button', { name: /guardar extras/i })); await waitFor(() => expect(saveDraft).toHaveBeenCalledWith('42', expect.objectContaining({ generalLaborAmount: 0, generalLaborVatApplies: false, items: [expect.objectContaining({ affectedPiece: 'Puerta', taskCode: '', actionCode: 'REPARAR', damageLevelCode: 'LEVE', partsAmount: 0, laborUnitAmount: 0 })] }))); const payload = saveDraft.mock.calls[0][1]; expect(payload).not.toHaveProperty('providerId'); expect(payload).not.toHaveProperty('comparison'); expect(payload).not.toHaveProperty('confirmation'); });
  it('uses the header lock returned by activation when the hydrated draft is saved immediately after', async () => { response = draft({ currentVersion: null, versionLock: null, activation: { active: false, requiresDeactivationConfirmation: false }, versions: [] }); const activated = draft({ currentVersion: 1, versionLock: 10 }); activation.mockResolvedValueOnce(activated); const view = render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); fireEvent.change(screen.getByLabelText('Activar trabajos extras'), { target: { value: 'SI' } }); await waitFor(() => expect(activation).toHaveBeenCalledWith('42', { expectedVersion: null, active: true, confirmDeactivation: false })); view.rerender(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); fireEvent.click(screen.getByRole('button', { name: /guardar extras/i })); await waitFor(() => expect(saveDraft).toHaveBeenCalledWith('42', expect.objectContaining({ expectedVersion: 10 }))); });
  it('does not dispatch a second draft mutation while the first save is in flight', () => { let resolveSave; saveDraft.mockImplementationOnce(() => new Promise((resolve) => { resolveSave = resolve; })); render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); const save = screen.getByRole('button', { name: /guardar extras/i }); fireEvent.click(save); fireEvent.click(save); expect(saveDraft).toHaveBeenCalledTimes(1); resolveSave(response); });
  it('saves a pre-existing draft with its header lock, then reloads after a genuinely stale header lock returns 409', async () => { const conflict = Object.assign(new Error('La versión cambió'), { httpStatus: 409 }); response = draft({ currentVersion: 3, versionLock: 27, versions: [{ ...draft().versions[0], number: 3 }] }); saveDraft.mockRejectedValueOnce(conflict); getExtraBudget.mockResolvedValueOnce(draft({ currentVersion: 3, versionLock: 28, versions: [{ ...draft().versions[0], number: 3 }] })); render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); fireEvent.click(screen.getByRole('button', { name: /guardar extras/i })); await waitFor(() => expect(saveDraft).toHaveBeenCalledWith('42', expect.objectContaining({ expectedVersion: 27 }))); await waitFor(() => expect(getExtraBudget).toHaveBeenCalledWith('42')); expect(screen.getByRole('dialog')).toHaveTextContent(/estado actual del servidor/i); expect(saveDraft).toHaveBeenCalledTimes(1); });
  it('confirms with the exact header lock returned by the preceding draft save', async () => { const saved = draft({ versionLock: 10 }); saveDraft.mockResolvedValueOnce(saved); const view = render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); fireEvent.click(screen.getByRole('button', { name: /guardar extras/i })); await waitFor(() => expect(setQueryData).toHaveBeenCalledWith(['cases', '42', 'extra-budget'], saved)); view.rerender(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); fireEvent.change(screen.getByLabelText('¿El cliente acepta el presupuesto?'), { target: { value: 'SI' } }); await waitFor(() => expect(confirm).toHaveBeenCalledWith('42', { expectedVersion: 10, confirmation: 'SI' })); });
  it('shows errors at the incomplete row fields instead of a global every-row error', () => { response = draft({ versions: [{ ...draft().versions[0], items: [{ itemId: 1, affectedPiece: '', actionCode: '', damageLevelCode: '', partsAmount: '-1', active: true }] }] }); render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); fireEvent.click(screen.getByRole('button', { name: /guardar extras/i })); expect(screen.getByText('Indicá la pieza afectada.')).toBeInTheDocument(); expect(screen.getByText('Elegí la tarea a ejecutar.')).toBeInTheDocument(); expect(screen.getByText('Elegí el nivel de daño.')).toBeInTheDocument(); expect(screen.getByText('Ingresá un importe igual o mayor a cero.')).toBeInTheDocument(); expect(saveDraft).not.toHaveBeenCalled(); });
  it('does not render V73 isolated quote controls and renders the V78 common extra matrix after rehydration', () => { response = draft({ versions: [{ ...draft().versions[0], items: [{ itemId: 900, affectedPiece: 'Espejo', actionCode: 'REEMPLAZAR', damageLevelCode: 'LEVE', partsAmount: 50, active: true }] }] }); render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); expect(screen.getByTestId('common-comparison')).toHaveTextContent('EXTRA'); expect(screen.getByText('Trabajo extra')).toBeInTheDocument(); expect(screen.queryByText(/cotizaciones extras aisladas/i)).toBeNull(); expect(screen.queryByRole('button', { name: /cotizar extra/i })).toBeNull(); });
  it('hydrates Pending and persists Sí and No independently', async () => { const view = render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); const selector = screen.getByLabelText('¿El cliente acepta el presupuesto?'); expect(selector).toHaveValue('PENDIENTE'); fireEvent.change(selector, { target: { value: 'SI' } }); await waitFor(() => expect(confirm).toHaveBeenCalledWith('42', { expectedVersion: 9, confirmation: 'SI' })); response = draft({ customerConfirmation: 'NO' }); view.rerender(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); expect(screen.getByLabelText('¿El cliente acepta el presupuesto?')).toHaveValue('NO'); fireEvent.change(screen.getByLabelText('¿El cliente acepta el presupuesto?'), { target: { value: 'NO' } }); await waitFor(() => expect(confirm).toHaveBeenLastCalledWith('42', { expectedVersion: 9, confirmation: 'NO' })); });
  it('keeps payment hidden for Pending and No, and shows it only after hydrated Sí acceptance', () => { const { rerender } = render(<ExtraBudgetPaymentsPanel caseId="42" caseTypeCode="TODO_RIESGO" />); expect(screen.queryByRole('button', { name: /registrar pago/i })).toBeNull(); response = draft({ customerConfirmation: 'SI', currentStatus: 'ACEPTADO', balance: 100, versions: [{ ...draft().versions[0], status: 'ACEPTADO' }] }); rerender(<ExtraBudgetPaymentsPanel caseId="42" caseTypeCode="TODO_RIESGO" />); expect(screen.getByRole('button', { name: /registrar pago/i })).toBeInTheDocument(); });
  it('shows the concurrent conflict feedback for a blocked Sí to No reversal', async () => { const conflict = Object.assign(new Error('No puede revertirse con pagos'), { httpStatus: 409 }); confirm.mockRejectedValueOnce(conflict); response = draft({ customerConfirmation: 'SI' }); render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); fireEvent.change(screen.getByLabelText('¿El cliente acepta el presupuesto?'), { target: { value: 'NO' } }); await waitFor(() => expect(screen.getByRole('dialog')).toHaveTextContent(/estado actual del servidor/i)); });
  it('reloads the current header after a truly stale confirmation lock returns 409', async () => { const conflict = Object.assign(new Error('La versión cambió'), { httpStatus: 409 }); response = draft({ versionLock: 27 }); confirm.mockRejectedValueOnce(conflict); getExtraBudget.mockResolvedValueOnce(draft({ versionLock: 28 })); render(<ExtraBudgetEditorPanel caseId="42" caseTypeCode="TODO_RIESGO" />); fireEvent.change(screen.getByLabelText('¿El cliente acepta el presupuesto?'), { target: { value: 'SI' } }); await waitFor(() => expect(confirm).toHaveBeenCalledWith('42', { expectedVersion: 27, confirmation: 'SI' })); await waitFor(() => expect(getExtraBudget).toHaveBeenCalledWith('42')); expect(screen.getByRole('dialog')).toHaveTextContent(/estado actual del servidor/i); });
});
