import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BriefcaseBusiness, Plus, Save } from 'lucide-react';
import { toast } from 'sonner';
import { DocumentsSection } from '@/modules/cases/components/documents-section';
import { createLegalExpense, createLegalInjuredParty, createLegalNews, getCasePersons, getLegalCase, getLegalExpenses, getLegalInjuredParties, getLegalNews, saveLegalCase } from '@/modules/cases/api/third-party-api';
import { requestJson } from '@/shared/api/http-client';
import { Button } from '@/shared/ui/button';
import { Input } from '@/shared/ui/input';
import { Textarea } from '@/shared/ui/textarea';

const Field = ({ label, children }) => <label className="block text-[11px] font-semibold uppercase tracking-[0.14em] text-muted-foreground"><span className="mb-1 block">{label}</span>{children}</label>;
const legalForm = (data) => ({ processorCode: data?.processorCode ?? '', claimantCode: data?.claimantCode ?? '', instanceCode: data?.instanceCode ?? '', entryDate: data?.entryDate ?? '', cuij: data?.cuij ?? '', court: data?.court ?? '', caseNumber: data?.caseNumber ?? '', counterpartLawyer: data?.counterpartLawyer ?? '', counterpartPhone: data?.counterpartPhone ?? '', counterpartEmail: data?.counterpartEmail ?? '', repairsVehicle: data?.repairsVehicle ?? true, closedByCode: data?.closedByCode ?? '', legalCloseDate: data?.legalCloseDate ?? '', totalProceedsAmount: data?.totalProceedsAmount ?? '', observations: data?.observations ?? '', closingNotes: data?.closingNotes ?? '' });
const numberOrNull = (value) => value === '' ? null : Number(value);

export const ThirdPartyLawyerEditor = ({ caseId }) => {
  const queryClient = useQueryClient(); const [form, setForm] = useState(() => legalForm(null));
  const [news, setNews] = useState({ newsDate: '', detail: '', notifyCustomer: false }); const [expense, setExpense] = useState({ concept: '', amount: '', expenseDate: '', paidByCode: '', sumsToWorkshop: false }); const [injured, setInjured] = useState({ lesionadoEsCode: 'OTRO', personId: '', fullName: '', documentNumber: '', provesIncome: false });
  const legalQuery = useQuery({ queryKey: ['cases', String(caseId), 'legal'], queryFn: () => getLegalCase(caseId) }); const catalogsQuery = useQuery({ queryKey: ['insurance', 'catalogs'], queryFn: () => requestJson('/insurance/catalogs') }); const casePersonsQuery = useQuery({ queryKey: ['cases', String(caseId), 'persons'], queryFn: () => getCasePersons(caseId) }); const newsQuery = useQuery({ queryKey: ['cases', String(caseId), 'legal-news'], queryFn: () => getLegalNews(caseId) }); const expensesQuery = useQuery({ queryKey: ['cases', String(caseId), 'legal-expenses'], queryFn: () => getLegalExpenses(caseId) }); const injuredQuery = useQuery({ queryKey: ['cases', String(caseId), 'legal-injured'], queryFn: () => getLegalInjuredParties(caseId) });
  useEffect(() => setForm(legalForm(legalQuery.data)), [legalQuery.data]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['cases', String(caseId)] });
  const saveMutation = useMutation({ mutationFn: () => saveLegalCase(caseId, { ...form, entryDate: form.entryDate || null, cuij: form.cuij || null, court: form.court || null, caseNumber: form.caseNumber || null, counterpartLawyer: form.counterpartLawyer || null, counterpartPhone: form.counterpartPhone || null, counterpartEmail: form.counterpartEmail || null, closedByCode: form.closedByCode || null, legalCloseDate: form.legalCloseDate || null, totalProceedsAmount: numberOrNull(form.totalProceedsAmount), observations: form.observations || null, closingNotes: form.closingNotes || null }), onSuccess: async () => { await refresh(); await queryClient.invalidateQueries({ queryKey: ['cases', String(caseId), 'workspace'] }); toast.success('Expediente guardado.'); }, onError: (e) => toast.error(e.message || 'No se pudo guardar el expediente.') });
  const newsMutation = useMutation({ mutationFn: () => createLegalNews(caseId, news), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['cases', String(caseId), 'legal-news'] }); setNews({ newsDate: '', detail: '', notifyCustomer: false }); toast.success('Novedad registrada.'); }, onError: (e) => toast.error(e.message) });
  const expenseMutation = useMutation({ mutationFn: () => createLegalExpense(caseId, { ...expense, amount: Number(expense.amount), expenseDate: expense.expenseDate || null, paidByCode: expense.paidByCode || null, financialMovementId: null }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['cases', String(caseId), 'legal-expenses'] }); setExpense({ concept: '', amount: '', expenseDate: '', paidByCode: '', sumsToWorkshop: false }); toast.success('Erogación registrada.'); }, onError: (e) => toast.error(e.message) });
  const injuredMutation = useMutation({ mutationFn: () => createLegalInjuredParty(caseId, { ...injured, personId: injured.personId ? Number(injured.personId) : null, fullName: injured.personId ? null : (injured.fullName || null), documentNumber: injured.documentNumber || null }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['cases', String(caseId), 'legal-injured'] }); setInjured({ lesionadoEsCode: 'OTRO', personId: '', fullName: '', documentNumber: '', provesIncome: false }); toast.success('Lesionado registrado.'); }, onError: (e) => toast.error(e.message) });
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value })); const catalogs = catalogsQuery.data ?? {}; const judicial = form.instanceCode === 'JUDICIAL'; const hasInjuries = ['DANIO_MATERIAL_LESIONES', 'FRANQUICIA_LESIONES'].includes(form.claimantCode);
  return <div className="space-y-5"><section className="rounded-3xl border border-border/70 bg-card p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-primary/10 text-primary"><BriefcaseBusiness className="h-5 w-5" /></div><h4 className="text-sm font-semibold">Expediente del abogado</h4></div><Button size="sm" onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending}><Save className="mr-1.5 h-3.5 w-3.5" />Guardar</Button></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Field label="Tramita"><Select value={form.processorCode} onChange={(e) => set('processorCode', e.target.value)} options={catalogs.legalProcessorCodes} /></Field><Field label="Reclama"><Select value={form.claimantCode} onChange={(e) => set('claimantCode', e.target.value)} options={catalogs.legalClaimantCodes} /></Field><Field label="Instancia"><Select value={form.instanceCode} onChange={(e) => set('instanceCode', e.target.value)} options={catalogs.legalInstanceCodes} /></Field><Field label="Fecha de ingreso"><Input type="date" value={form.entryDate} onChange={(e) => set('entryDate', e.target.value)} /></Field><Field label="Repara vehículo"><select value={form.repairsVehicle ? 'SI' : 'NO'} onChange={(e) => set('repairsVehicle', e.target.value === 'SI')} className="h-10 w-full rounded-xl border border-input bg-background px-3 text-sm"><option value="SI">Sí</option><option value="NO">No</option></select></Field>{judicial ? <><Field label="Nº CUIJ"><Input value={form.cuij} onChange={(e) => set('cuij', e.target.value)} /></Field><Field label="Juzgado"><Input value={form.court} onChange={(e) => set('court', e.target.value)} /></Field><Field label="Autos"><Input value={form.caseNumber} onChange={(e) => set('caseNumber', e.target.value)} /></Field></> : null}<Field label="Abogado contraparte"><Input value={form.counterpartLawyer} onChange={(e) => set('counterpartLawyer', e.target.value)} /></Field><Field label="Teléfono contraparte"><Input value={form.counterpartPhone} onChange={(e) => set('counterpartPhone', e.target.value)} /></Field><Field label="Email contraparte"><Input type="email" value={form.counterpartEmail} onChange={(e) => set('counterpartEmail', e.target.value)} /></Field></div><Field label="Observaciones y antecedentes"><Textarea className="mt-1 min-h-24" value={form.observations} onChange={(e) => set('observations', e.target.value)} /></Field></section>
    {hasInjuries ? <Section title="Lesionados"><div className="grid gap-3 md:grid-cols-4"><Field label="Lesionado es"><Select value={injured.lesionadoEsCode} onChange={(e) => setInjured((x) => ({ ...x, lesionadoEsCode: e.target.value, personId: '', fullName: '' }))} options={catalogs.lesionadoEsCodes} /></Field>{injured.lesionadoEsCode === 'OTRO' ? <Field label="Nombre"><Input value={injured.fullName} onChange={(e) => setInjured((x) => ({ ...x, fullName: e.target.value }))} /></Field> : <Field label="Persona"><select value={injured.personId} onChange={(e) => setInjured((x) => ({ ...x, personId: e.target.value }))} className="h-10 w-full rounded-xl border border-input bg-background px-3 text-sm"><option value="">Seleccionar…</option>{(casePersonsQuery.data ?? []).filter((person) => injured.lesionadoEsCode === 'CLIENTE' ? person.principal : person.caseRoleCode === 'TITULAR').map((person) => <option key={person.id} value={person.personId}>{person.displayName}</option>)}</select></Field>}<Field label="Documento"><Input value={injured.documentNumber} onChange={(e) => setInjured((x) => ({ ...x, documentNumber: e.target.value }))} /></Field><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={injured.provesIncome} onChange={(e) => setInjured((x) => ({ ...x, provesIncome: e.target.checked }))} />Acredita ingresos</label></div><Button className="mt-3" size="sm" onClick={() => injuredMutation.mutate()} disabled={(!injured.fullName && !injured.personId) || injuredMutation.isPending}><Plus className="mr-1.5 h-3.5 w-3.5" />Agregar lesionado</Button><List items={injuredQuery.data} render={(item) => `${item.fullName || item.personId} · ${item.provesIncome ? 'Acredita ingresos' : 'No acredita ingresos'}`} /></Section> : null}
    <DocumentsSection caseId={caseId} />
    <Section title="Estado de expediente"><div className="grid gap-3 md:grid-cols-[160px_1fr_auto]"><Input type="date" value={news.newsDate} onChange={(e) => setNews((x) => ({ ...x, newsDate: e.target.value }))} /><Input value={news.detail} placeholder="Novedad" onChange={(e) => setNews((x) => ({ ...x, detail: e.target.value }))} /><Button size="sm" onClick={() => { if (!news.notifyCustomer || window.confirm('¿Confirma la notificación al cliente?')) newsMutation.mutate(); }} disabled={!news.newsDate || !news.detail || newsMutation.isPending}>Agregar</Button></div><label className="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={news.notifyCustomer} onChange={(e) => setNews((x) => ({ ...x, notifyCustomer: e.target.checked }))} />Notificar al cliente</label><List items={newsQuery.data} render={(item) => `${item.newsDate}: ${item.detail}${item.notifyCustomer ? ' · Notificar cliente' : ''}`} /></Section>
    <Section title="Cierre y erogaciones"><div className="grid gap-3 md:grid-cols-3"><Field label="Cierre por"><Select value={form.closedByCode} onChange={(e) => set('closedByCode', e.target.value)} options={catalogs.legalClosureReasonCodes} /></Field><Field label="Fecha de cierre"><Input type="date" value={form.legalCloseDate} onChange={(e) => set('legalCloseDate', e.target.value)} /></Field><Field label="Importe total"><Input type="number" min="0" value={form.totalProceedsAmount} onChange={(e) => set('totalProceedsAmount', e.target.value)} /></Field></div><Textarea className="mt-3 min-h-20" placeholder="Notas de cierre" value={form.closingNotes} onChange={(e) => set('closingNotes', e.target.value)} /><div className="mt-3 grid gap-3 md:grid-cols-4"><Input placeholder="Concepto" value={expense.concept} onChange={(e) => setExpense((x) => ({ ...x, concept: e.target.value }))} /><Input type="number" min="0" placeholder="Monto" value={expense.amount} onChange={(e) => setExpense((x) => ({ ...x, amount: e.target.value }))} /><Input type="date" value={expense.expenseDate} onChange={(e) => setExpense((x) => ({ ...x, expenseDate: e.target.value }))} /><select value={expense.paidByCode} onChange={(e) => setExpense((x) => ({ ...x, paidByCode: e.target.value }))} className="h-10 rounded-xl border border-input bg-background px-3 text-sm"><option value="">Pagado por…</option>{(catalogs.legalExpensePayerCodes ?? []).map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={expense.sumsToWorkshop} onChange={(e) => setExpense((x) => ({ ...x, sumsToWorkshop: e.target.checked }))} />Suma Taller</label><Button className="mt-3" size="sm" onClick={() => expenseMutation.mutate()} disabled={!expense.concept || !expense.amount || !expense.expenseDate || expenseMutation.isPending}>Agregar gasto</Button><List items={expensesQuery.data} render={(item) => `${item.expenseDate}: ${item.concept} · $${item.amount}${item.sumsToWorkshop ? ' · Suma taller' : ''}`} /></Section>
  </div>;
};
const Select = ({ value, onChange, options = [] }) => <select value={value} onChange={onChange} className="h-10 w-full rounded-xl border border-input bg-background px-3 text-sm"><option value="">Seleccionar…</option>{options.map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}</select>;
const Section = ({ title, children }) => <section className="rounded-3xl border border-border/70 bg-card p-5"><h4 className="text-sm font-semibold">{title}</h4><div className="mt-4">{children}</div></section>;
const List = ({ items = [], render }) => items.length ? <ul className="mt-4 space-y-1 text-sm text-muted-foreground">{items.map((item) => <li key={item.id} className="rounded-xl bg-muted/40 px-3 py-2">{render(item)}</li>)}</ul> : null;
