export function createAuthenticatedCaseDetailInitialState() {
  return {
    status: 'idle',
    tone: 'info',
    title: 'Detalle pendiente',
    detail: 'Elegí una carpeta para ver un resumen real del caso.',
    endpoint: '',
    checkedAt: '',
    httpStatus: null,
    item: null,
    data: null,
    workflowHistory: [],
    workflowActions: [],
    budgetState: {
      status: 'idle',
      data: null,
      items: [],
      totalItems: 0,
      detail: '',
    },
    appointmentsState: {
      status: 'idle',
      items: [],
      total: 0,
      nextAppointment: null,
      hasUpcomingAppointment: false,
      detail: '',
    },
    documentsState: {
      status: 'idle',
      items: [],
      total: 0,
      visibleCount: 0,
      hiddenCount: 0,
      detail: '',
    },
    financeSummaryState: {
      status: 'idle',
      data: null,
      detail: '',
    },
    financialMovementsState: {
      status: 'idle',
      items: [],
      total: 0,
      detail: '',
    },
    receiptsState: {
      status: 'idle',
      items: [],
      total: 0,
      latest: null,
      detail: '',
    },
    vehicleIntakesState: {
      status: 'idle',
      items: [],
      total: 0,
      latest: null,
      detail: '',
    },
    vehicleOutcomesState: {
      status: 'idle',
      items: [],
      total: 0,
      latest: null,
      detail: '',
    },
    trackingNotice: '',
  };
}
