package com.tallerzapata.backend.application.insurance;

import com.tallerzapata.backend.api.insurance.*;
import com.tallerzapata.backend.application.casefile.CaseAuditService;
import com.tallerzapata.backend.application.casefile.InsuranceRepairCasePolicy;
import com.tallerzapata.backend.application.common.ConflictException;
import com.tallerzapata.backend.application.common.ResourceNotFoundException;
import com.tallerzapata.backend.application.security.CaseAccessControlService;
import com.tallerzapata.backend.infrastructure.persistence.casefile.*;
import com.tallerzapata.backend.infrastructure.persistence.finance.FinancialMovementEntity;
import com.tallerzapata.backend.infrastructure.persistence.finance.FinancialMovementRepository;
import com.tallerzapata.backend.infrastructure.persistence.insurance.*;
import com.tallerzapata.backend.infrastructure.security.*;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.time.LocalDateTime;
import java.util.List;

@Service
public class LegalRecoverableItemService {
    private final CaseRepository caseRepository; private final CaseTypeRepository caseTypeRepository; private final CaseLegalRepository legalRepository; private final LegalRecoverableItemRepository itemRepository; private final FinancialMovementRepository movementRepository; private final CurrentUserService currentUserService; private final CaseAccessControlService access; private final CaseAuditService audit; private final InsuranceRepairCasePolicy policy = new InsuranceRepairCasePolicy();
    public LegalRecoverableItemService(CaseRepository caseRepository, CaseTypeRepository caseTypeRepository, CaseLegalRepository legalRepository, LegalRecoverableItemRepository itemRepository, FinancialMovementRepository movementRepository, CurrentUserService currentUserService, CaseAccessControlService access, CaseAuditService audit) { this.caseRepository=caseRepository; this.caseTypeRepository=caseTypeRepository; this.legalRepository=legalRepository; this.itemRepository=itemRepository; this.movementRepository=movementRepository; this.currentUserService=currentUserService; this.access=access; this.audit=audit; }
    @Transactional(readOnly = true) public List<LegalRecoverableItemResponse> list(Long caseId) { CaseEntity c=requireLawyerCase(caseId, "seguro.ver"); CaseLegalEntity legal=legalRepository.findByCaseId(caseId).orElseThrow(() -> new ResourceNotFoundException("Falta expediente legal")); return itemRepository.findByCaseLegalIdOrderByIdAsc(legal.getId()).stream().map(this::response).toList(); }
    @Transactional public LegalRecoverableItemResponse create(Long caseId, LegalRecoverableItemCreateRequest request, HttpServletRequest http) { AuthenticatedUser user=currentUserService.requireCurrentUser(); CaseEntity c=requireLawyerCase(caseId, "seguro.crear"); if(request.concept()==null||request.concept().isBlank()||request.amount()==null||request.amount().signum()<0) throw new ConflictException("Concepto y monto no negativo son obligatorios"); CaseLegalEntity legal=legalRepository.findByCaseId(caseId).orElseThrow(() -> new ConflictException("Debe crear primero el expediente legal")); LegalRecoverableItemEntity item=new LegalRecoverableItemEntity(); item.setCaseLegalId(legal.getId()); item.setConcept(request.concept().trim()); item.setAmount(request.amount().setScale(2, RoundingMode.HALF_UP)); item.setSumsToWorkshop(Boolean.TRUE.equals(request.sumsToWorkshop())); item.setCollectionStatusCode("PENDIENTE"); item=itemRepository.save(item); audit.register(user.id(),caseId,"legal_rubros_recuperables",item.getId(),"crear_rubro_legal",null,audit.toJson(java.util.Map.of("amount",item.getAmount(),"sumaTaller",item.getSumsToWorkshop())),audit.toJson(java.util.Map.of("domain","legal")),http); return response(item); }
    @Transactional public LegalRecoverableItemResponse markCollected(Long caseId, Long itemId, HttpServletRequest http) { AuthenticatedUser user=currentUserService.requireCurrentUser(); CaseEntity c=requireLawyerCase(caseId,"seguro.crear"); LegalRecoverableItemEntity item=itemRepository.findById(itemId).orElseThrow(() -> new ResourceNotFoundException("No existe rubro legal")); CaseLegalEntity legal=legalRepository.findByCaseId(caseId).orElseThrow(() -> new ResourceNotFoundException("Falta expediente legal")); if(!item.getCaseLegalId().equals(legal.getId())) throw new ResourceNotFoundException("El rubro no pertenece al expediente"); if(!Boolean.TRUE.equals(item.getSumsToWorkshop())) throw new ConflictException("Solo los rubros que suman al taller pueden cobrarse en contabilidad"); if("COBRADO".equals(item.getCollectionStatusCode())) return response(item); FinancialMovementEntity movement=new FinancialMovementEntity(); movement.setCaseId(caseId); movement.setMovementTypeCode("INGRESO"); movement.setFlowOriginCode("LEGAL"); movement.setCounterpartyTypeCode("CAJA"); movement.setMovementAt(LocalDateTime.now()); movement.setGrossAmount(item.getAmount()); movement.setNetAmount(item.getAmount()); movement.setPaymentMethodCode("EFECTIVO"); movement.setCancellationTypeCode("RUBRO_LEGAL"); movement.setAdvancePayment(false); movement.setBonification(false); movement.setReason("Cobro rubro legal: " + item.getConcept()); movement.setRegisteredBy(user.id()); movement=movementRepository.save(movement); item.setFinancialMovementId(movement.getId()); item.setCollectionStatusCode("COBRADO"); item=itemRepository.save(item); audit.register(user.id(),caseId,"legal_rubros_recuperables",item.getId(),"cobrar_rubro_legal",null,audit.toJson(java.util.Map.of("financialMovementId",movement.getId(),"amount",item.getAmount())),audit.toJson(java.util.Map.of("domain","finanzas")),http); return response(item); }
    private CaseEntity requireLawyerCase(Long caseId,String permission){ AuthenticatedUser u=currentUserService.requireCurrentUser(); CaseEntity c=caseRepository.findById(caseId).orElseThrow(() -> new ResourceNotFoundException("No existe caso")); access.requireCaseAccess(u,c,permission); String type=caseTypeRepository.findById(c.getCaseTypeId()).map(CaseTypeEntity::getCode).orElse(""); if(!policy.isThirdPartyLawyerClaim(type)) throw new ConflictException("Rubros legales solo aplican a reclamos de terceros por abogado"); return c; }
    private LegalRecoverableItemResponse response(LegalRecoverableItemEntity x){return new LegalRecoverableItemResponse(x.getId(),x.getConcept(),x.getAmount(),x.getSumsToWorkshop(),x.getCollectionStatusCode(),x.getFinancialMovementId());}
}
