package com.tallerzapata.backend.application.insurance;

import com.tallerzapata.backend.api.insurance.*;
import com.tallerzapata.backend.application.casefile.CaseAuditService;
import com.tallerzapata.backend.application.casefile.InsuranceRepairCasePolicy;
import com.tallerzapata.backend.application.common.ConflictException;
import com.tallerzapata.backend.application.common.ResourceNotFoundException;
import com.tallerzapata.backend.application.security.CaseAccessControlService;
import com.tallerzapata.backend.infrastructure.persistence.casefile.*;
import com.tallerzapata.backend.infrastructure.persistence.finance.FinancialMovementEntity;
import com.tallerzapata.backend.infrastructure.persistence.finance.FinancialMovementRepository;
import com.tallerzapata.backend.infrastructure.persistence.insurance.*;
import com.tallerzapata.backend.infrastructure.security.*;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Service
public class LegalRecoverableItemService {
    private final CaseRepository caseRepository; private final CaseTypeRepository caseTypeRepository; private final CaseLegalRepository legalRepository; private final LegalRecoverableItemRepository itemRepository; private final FinancialMovementRepository movementRepository; private final CurrentUserService currentUserService; private final CaseAccessControlService access; private final CaseAuditService audit; private final InsuranceRepairCasePolicy policy = new InsuranceRepairCasePolicy();
    public LegalRecoverableItemService(CaseRepository caseRepository, CaseTypeRepository caseTypeRepository, CaseLegalRepository legalRepository, LegalRecoverableItemRepository itemRepository, FinancialMovementRepository movementRepository, CurrentUserService currentUserService, CaseAccessControlService access, CaseAuditService audit) { this.caseRepository=caseRepository; this.caseTypeRepository=caseTypeRepository; this.legalRepository=legalRepository; this.itemRepository=itemRepository; this.movementRepository=movementRepository; this.currentUserService=currentUserService; this.access=access; this.audit=audit; }
    @Transactional(readOnly = true) public List<LegalRecoverableItemResponse> list(Long caseId) { CaseLegalEntity legal=legalFor(caseId, "seguro.ver"); return itemRepository.findByCaseLegalIdOrderByIdAsc(legal.getId()).stream().filter(item -> Boolean.TRUE.equals(item.getActive())).map(this::response).toList(); }
    @Transactional public LegalRecoverableItemResponse create(Long caseId, LegalRecoverableItemCreateRequest request, HttpServletRequest http) { AuthenticatedUser user=currentUserService.requireCurrentUser(); CaseEntity c=requireLawyerCase(caseId, "seguro.crear"); validate(request.concept(), request.amount()); CaseLegalEntity legal=legalRepository.findByCaseId(caseId).orElseGet(() -> initializeLawyerLegalCase(c)); LegalRecoverableItemEntity item=new LegalRecoverableItemEntity(); item.setCaseLegalId(legal.getId()); apply(item, request.concept(), request.amount(), request.expectedPaymentDate(), request.sumsToWorkshop(), request.effectivePaymentDate(), caseId, user.id()); item.setActive(true); item=itemRepository.save(item); syncMovement(item, caseId, user.id()); item=itemRepository.save(item); audit.register(user.id(),caseId,"legal_rubros_recuperables",item.getId(),"crear_rubro_legal",null,audit.toJson(java.util.Map.of("amount",item.getAmount(),"sumaTaller",item.getSumsToWorkshop())),audit.toJson(java.util.Map.of("domain","legal")),http); return response(item); }
    @Transactional public LegalRecoverableItemResponse update(Long caseId, Long itemId, LegalRecoverableItemUpdateRequest request, HttpServletRequest http) { AuthenticatedUser user=currentUserService.requireCurrentUser(); LegalRecoverableItemEntity item=requireItem(legalFor(caseId, "seguro.crear"), itemId); validate(request.concept(), request.amount()); apply(item, request.concept(), request.amount(), request.expectedPaymentDate(), request.sumsToWorkshop(), request.effectivePaymentDate(), caseId, user.id()); syncMovement(item, caseId, user.id()); item=itemRepository.save(item); audit.register(user.id(),caseId,"legal_rubros_recuperables",item.getId(),"actualizar_rubro_legal",null,audit.toJson(java.util.Map.of("amount",item.getAmount(),"sumaTaller",item.getSumsToWorkshop())),audit.toJson(java.util.Map.of("domain","legal")),http); return response(item); }
    @Transactional public void delete(Long caseId, Long itemId, HttpServletRequest http) { AuthenticatedUser user=currentUserService.requireCurrentUser(); LegalRecoverableItemEntity item=requireItem(legalFor(caseId, "seguro.crear"), itemId); removeMovement(item); item.setActive(false); item.setFinancialMovementId(null); item=itemRepository.save(item); audit.register(user.id(),caseId,"legal_rubros_recuperables",item.getId(),"eliminar_rubro_legal",null,null,audit.toJson(java.util.Map.of("domain","legal")),http); }
    @Transactional public LegalRecoverableItemResponse markCollected(Long caseId, Long itemId, HttpServletRequest http) { AuthenticatedUser user=currentUserService.requireCurrentUser(); LegalRecoverableItemEntity item=requireItem(legalFor(caseId,"seguro.crear"), itemId); if(!Boolean.TRUE.equals(item.getSumsToWorkshop())) throw new ConflictException("Solo los rubros que suman al taller pueden cobrarse en contabilidad"); item.setEffectivePaymentDate(LocalDate.now()); item.setCollectionStatusCode("COBRADO"); syncMovement(item, caseId, user.id()); item=itemRepository.save(item); audit.register(user.id(),caseId,"legal_rubros_recuperables",item.getId(),"cobrar_rubro_legal",null,audit.toJson(java.util.Map.of("financialMovementId",item.getFinancialMovementId(),"amount",item.getAmount())),audit.toJson(java.util.Map.of("domain","finanzas")),http); return response(item); }
    private CaseLegalEntity legalFor(Long caseId, String permission) { CaseEntity c=requireLawyerCase(caseId, permission); return legalRepository.findByCaseId(caseId).orElseThrow(() -> new ResourceNotFoundException("Falta expediente legal")); }
    private LegalRecoverableItemEntity requireItem(CaseLegalEntity legal, Long itemId) { LegalRecoverableItemEntity item=itemRepository.findById(itemId).orElseThrow(() -> new ResourceNotFoundException("No existe rubro legal")); if(!item.getCaseLegalId().equals(legal.getId()) || !Boolean.TRUE.equals(item.getActive())) throw new ResourceNotFoundException("El rubro no pertenece al expediente"); return item; }
    private void validate(String concept, BigDecimal amount) { if(concept==null||concept.isBlank()||amount==null||amount.signum()<=0) throw new ConflictException("Concepto y monto mayor a cero son obligatorios"); }
    private void apply(LegalRecoverableItemEntity item, String concept, BigDecimal amount, LocalDate expected, Boolean sums, LocalDate effective, Long caseId, Long userId) { item.setConcept(concept.trim()); item.setAmount(amount.setScale(2, RoundingMode.HALF_UP)); item.setExpectedPaymentDate(expected); item.setSumsToWorkshop(Boolean.TRUE.equals(sums)); item.setEffectivePaymentDate(effective); item.setCollectionStatusCode(effective == null ? "PENDIENTE" : "COBRADO"); if (!Boolean.TRUE.equals(sums)) { removeMovement(item); item.setFinancialMovementId(null); } }
    private void syncMovement(LegalRecoverableItemEntity item, Long caseId, Long userId) { if (!Boolean.TRUE.equals(item.getSumsToWorkshop())) return; FinancialMovementEntity movement=item.getFinancialMovementId()==null ? new FinancialMovementEntity() : movementRepository.findById(item.getFinancialMovementId()).orElse(new FinancialMovementEntity()); movement.setCaseId(caseId); movement.setMovementTypeCode("INGRESO"); movement.setFlowOriginCode("LEGAL"); movement.setCounterpartyTypeCode("CAJA"); movement.setMovementAt((item.getEffectivePaymentDate()!=null ? item.getEffectivePaymentDate() : item.getExpectedPaymentDate()!=null ? item.getExpectedPaymentDate() : LocalDate.now()).atStartOfDay()); movement.setGrossAmount(item.getAmount()); movement.setNetAmount(item.getAmount()); movement.setPaymentMethodCode("EFECTIVO"); movement.setCancellationTypeCode("RUBRO_LEGAL"); movement.setAdvancePayment(false); movement.setBonification(false); movement.setReason("Rubro legal: " + item.getConcept()); movement.setExternalReference("LEGAL_RUBRO:" + item.getId()); movement.setCollectionStatusCode(item.getCollectionStatusCode()); movement.setRegisteredBy(userId); movement=movementRepository.save(movement); item.setFinancialMovementId(movement.getId()); }
    private void removeMovement(LegalRecoverableItemEntity item) { if (item.getFinancialMovementId()!=null) movementRepository.deleteById(item.getFinancialMovementId()); }
    private CaseEntity requireLawyerCase(Long caseId,String permission){ AuthenticatedUser u=currentUserService.requireCurrentUser(); CaseEntity c=caseRepository.findById(caseId).orElseThrow(() -> new ResourceNotFoundException("No existe caso")); access.requireCaseAccess(u,c,permission); String type=caseTypeRepository.findById(c.getCaseTypeId()).map(CaseTypeEntity::getCode).orElse(""); if(!policy.isThirdPartyLawyerClaim(type)) throw new ConflictException("Rubros legales solo aplican a reclamos de terceros por abogado"); return c; }
    private CaseLegalEntity initializeLawyerLegalCase(CaseEntity caseEntity){ CaseLegalEntity legal=new CaseLegalEntity(); legal.setCaseId(caseEntity.getId()); legal.setRepairsVehicle(true); return legalRepository.save(legal); }
    private LegalRecoverableItemResponse response(LegalRecoverableItemEntity x){return new LegalRecoverableItemResponse(x.getId(),x.getConcept(),x.getAmount(),x.getExpectedPaymentDate(),x.getSumsToWorkshop(),x.getEffectivePaymentDate(),x.getCollectionStatusCode(),x.getFinancialMovementId(),x.getActive());}
}
